name: build

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - run: ./build.sh
      - uses: AButler/upload-release-assets@v2.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          files: fluent-bit/build/bin/fluent-bit

